- name: "Flask App"
  hosts: amazon
  become: true
  vars:
    packages:
      - git
      - python3
      - pip
    user: "flask-user"
    group: "flask-user"
    working_directory: "/var/flask-app"
    repo_url: "https://github.com/Prince-Philip-Kadavil/Flask_app_Unit_file.git"

  tasks:
    - name: "Installing required packages"
      yum:
        name: "{{ packages }}"
        state: present

    - name: "Installing Flask"
      pip:
        name: flask
        state: present

    - name: "Cloning or updating Flask app and unit file from GIT Repo"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ working_directory }}"
        update: yes
      register: gitclone_status

    - name: "Copying files"
      when: gitclone_status.changed == true
      copy:
        src: "{{ working_directory }}/app.service"
        dest: "/etc/systemd/system/app.service"
        remote_src: true
        owner: root
        group: root
        mode: '0644'

    - name: "Creating group flask-user"
      group:
        name: "{{ user }}"
        state: present

    - name: "Creating user flask-user"
      user:
        name: "{{ user }}"
        home: "{{ working_directory }}"
        group: "{{ group }}"
        state: present

    - name: "Updating permissions of flask-user home directory"
      file:
        path: "{{ working_directory }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: '0755'

    - name: "Add public key for key based authentication"
      authorized_key:
        key: "{{ lookup('file', '~/flask_key.pub') }}"
        user: "{{ user }}"
        state: present

    - name: Reload systemd
      when: gitclone_status.changed == true
      systemd:
        daemon_reload: yes

    - name: Ensure service is enabled and running
      when: gitclone_status.changed == true
      systemd:
        name: app
        enabled: yes
        state: restarted
